### ISSUE TITLE
sftp-sink connector example fails

### ISSUE THREAD

**Issue by huynconfluent** [vdesabou/kafka-docker-playground#2068]
Needed to test the sftp-sink connector, but found that the sftp-server container would fail when running the `sftp-sink.sh` command.

Looking at the log output of that container I see.
```
[/usr/local/bin/create-sftp-user] Parsing user data: "foo:pass:::upload"
cat: /home/foo/.ssh/keys/id_rsa.pub: Is a directory
/usr/local/bin/create-sftp-user: Error on line 90: cat "$publickey" >> "$userKeysAllowedFileTmp"
/entrypoint: Error on line 60: create-sftp-user "$user"
```

Looking at the connect-sftp-sink directory, I see that these 2 directories are created.
```
drwxr-xr-x  2 huy.nguyen  staff    64B Jan  6 10:41 ssh_host_rsa_key.pem/
drwxr-xr-x  2 huy.nguyen  staff    64B Jan  6 10:41 ssh_host_rsa_key.pub/
```

Hence why the above is failing. What's also strange is if I'm looking at the docker-compose file, the volume mount suggest it's only used with the `sftp-sink-ssh-key.sh` and not `sftp-sink.sh`
```
sftp-server:
    image: atmoz/sftp
    hostname: sftp-server
    container_name: sftp-server
    ports:
      - "2222:22"
    command: foo:pass:::upload
    volumes:
      # for sftp-sink-ssh-key.sh
      - ../../connect/connect-sftp-sink/ssh_host_rsa_key.pub:/home/foo/.ssh/keys/id_rsa.pub:ro
```

So what we end up with when running `sftp-sink.sh` is

```
10:42:33 ℹ️ Sending messages to topic test_sftp_sink
10:42:47 ℹ️ Listing content of ./upload/topics/test_sftp_sink/partition\=0/
Error response from daemon: Container c9430fb91a8caea1f7453f0f072609464be69ff2ba9edaa5f772c17b6526d938 is not running
```
